DESIGN_NAME: spi_top
VERILOG_FILES:
- src/spi_init.sv
- src/nfc_spi.sv
- src/eeprom_spi.sv
- src/axi_lite_master.sv
- src/axi_spi_master/

USE_SLANG: true

# 30% because the design is too small.
FP_CORE_UTIL: 30

FP_ASPECT_RATIO: 1.0
PL_TARGET_DENSITY: 0.55
